# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c39822a04a110b99afedd78d26ae060ac47fc4662ca8804f54efdb20f10a53bbb7881f6ddb636079b8d0399ee213df8bf144c6f2abc11fb3d2ed8a56ad1e917

test:
  secret_key_base: 98ff866fa8f1c23ea2e77b004ac1c2f0a1fd92eefab3bf073d759e6ef41e8a447473be52c5acb69a1cce6ef9c32b69fbc6cdba33368ade0fac4d9de7e6f78be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
