version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: prospring5
      MYSQL_PASSWORD: prospring5
      MYSQL_DATABASE: musicdb
      MYSQL_ROOT_HOST: '%'
    volumes:
      - '/var/lib/mysql:/var/lib/mysql'
  micro:
    image: payara/micro
  server-full:
    image: payara/server-full
volumes:
  musicdb: null
