#============== Open API =============================================================================
springdoc:
  api-docs.enabled: true
  swagger-ui.disable-swagger-default-url: true
#  swagger-ui.use-root-path: true
#  swagger-ui.configUrl: "/v3/api-docs/"
#  swagger-ui.path: "/swagger-ui.html"

#============== Actuator ==============================================================================
management:
  endpoint:
    health:
      show-details: always
    metrics.enabled: true
  endpoints:
    web:
      discovery:
        enabled: true
      base-path: /actuator
      path-mapping:
        health: /health
      exposure:
        include: "*"
        # exclude: env,beans,mapping,configprops
  server:
    add-application-context-header: true
    port: 5090
    # address: 127.0.0.1 access to the endpoints is restricted only to 127.0.0.1
#    metrics:
#       export:
#             graphite:
#                step: 3s
#
#============== Server ==============================================================================
server:
  error.include-message: always
  http2:
    enabled: true
  compression:
    enabled: true
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
#    ssl:
#        enabled: true
#        key-store: classpath:keystore.jks
#        key-store-type: PKCS12
#        key-store-password: password
#        key-password: password
#        key-alias: sb2-recipes

#============== Spring ==============================================================================
spring:
  kafka.bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9093}
  mvc.static-path-pattern: /swagger*
  #    cloud:
  #        gcp:
  #             logging:
  #                 enabled: true
  #             trace:
  #                 enabled: true

  #============== Messages =============================================================================
  messages:
    always-use-message-format: true
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false # Recommended during development only.

  #============== Data Source ===========================================================================
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    hikari:
      poolName: SpringBootJPAHikariCP
      connectionTimeout: 60000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generated-statistics: false
        show-sql: false
        jdbc:
          time-zone: GMT-3
      cache:
        region:
          factory-class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        use-query-cache: true
        use-second-level-cache: true
      javax:
        persistence:
          retrieveMode:
            mode: ENABLE_SELECTIVE
          sharedCache:
            mode: ENABLE_SELECTIVE
