INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (1, 5,'Penny')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (2, 17,'Sheldon')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (3, 25,'Amy')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (4, 22,'Leonard')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (5, 55,'Bernadette')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (6, 45,'Raj')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (7, 6,'Howard')
INSERT INTO STUDENT("ID", "AGE", "NAME") VALUES (8, 30,'Priya')


INSERT INTO BOOK("ID", "STUDENT_ID", "NAME") VALUES (1, 2,'Treasure Island')
INSERT INTO BOOK("ID", "STUDENT_ID", "NAME") VALUES (2, 4,'The Java Man')

