package br.com.fernando.chapter13_javaPersistence.part05_schemaGeneration;

import static br.com.fernando.Util.APP_FILE_TARGET;
import static br.com.fernando.Util.DATA_BASE_SERVER_LOGIN;
import static br.com.fernando.Util.DATA_BASE_SERVER_PASSWORD;
import static br.com.fernando.Util.DATA_BASE_SERVER_PORT;
import static br.com.fernando.Util.EMBEDDED_JEE_TEST_APP_NAME;
import static br.com.fernando.Util.EMBEDDED_JEE_TEST_DATA_SOURCE_NAME;
import static br.com.fernando.Util.HSQLDB_JDBC_DRIVER;
import static br.com.fernando.Util.HTTP_PORT;
import static br.com.fernando.Util.downVariables;
import static br.com.fernando.Util.startVariables;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.persistence.Column;
import javax.persistence.ConstraintMode;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClientBuilder;
import org.myembedded.jeecontainer.MyEmbeddedJeeContainer;
import org.myembedded.jeecontainer.resources.MyEmbeddedDataSource;
import org.myembedded.jeecontainer.resources.MyEmbeddedDataSource.MyEmbeddedDataSourceBuilder;
import org.myembedded.pack.EmbeddedResource;
import org.myembedded.pack.EmbeddedWar;
import org.myembedded.rdbms.MyEmbeddedRdbms;

public class SchemaGeneration02MetaData {

    // The usual annotations—such as @Table, @Column, @CollectionTable, @JoinTable, and @JoinColumn—are used to define the generated schema.
    //
    // Maps to the STUDENT table in the default schema.
    @Entity
    @Table(name = "STUDENT", //
	    // An index for the primary key is generated by default in a database.
	    // This new annotation will allow you to define additional indexes, over a single or multiple columns,
	    // for better performance.
	    indexes = { //
		    @Index(columnList = "NAME"), //
		    @Index(columnList = "AGE") //
	    } //
    )
    public static class Student implements Serializable {

	@Transient
	private static final long serialVersionUID = 1L;

	// The id field is mapped to the ID column as the primary key.
	@Id
	@Column(name = "ID")
	int id;

	@Column(name = "NAME")
	String name;

	@Column(name = "AGE")
	int age;

	@Override
	public String toString() {
	    StringBuilder builder = new StringBuilder();

	    builder.append("Student [id=").append(id) //
		    .append(", name=").append(name) //
		    .append("]");
	    return builder.toString();
	}
    }

    @Entity
    @Table(name = "BOOK")
    public static class Book {

	@Id
	@Column(name = "ID")
	int id;

	@Column(name = "NAME")
	String name;

	// This is used to define a foreign key constraint or to otherwise override or disable the persistence provider’s default foreign key definition.
	// It can be specified as part of JoinColumn(s), MapKeyJoinColumn(s), and PrimaryKeyJoinColumn(s):
	@ManyToOne
	@JoinColumn( //
		foreignKey = @ForeignKey( //
			name = "FK_STUDENT_BOOK", //
			foreignKeyDefinition = "FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT", //
			value = ConstraintMode.CONSTRAINT //
		) //
	)
	Student student;

	@Override
	public String toString() {
	    StringBuilder builder = new StringBuilder();

	    builder.append("Book [id=").append(id) //
		    .append(", name=").append(name) //
		    .append(", student=").append(student) //
		    .append("]");

	    return builder.toString();
	}
    }

    @Stateless
    public static class Service {

	@PersistenceContext(name = "MyPU")
	EntityManager em;

	public void persist(Student e) {
	    em.persist(e);
	}

	public List<Book> get() {
	    return em.createQuery("SELECT e FROM SchemaGeneration02MetaData$Book e", Book.class).getResultList();
	}
    }

    // ==================================================================================================================================================================
    @WebServlet("/ServletPrincipal")
    public static class ServletPrincipal extends HttpServlet {

	private static final long serialVersionUID = 1L;

	@Inject
	Service service;

	@Override
	protected void doGet(final HttpServletRequest req, final HttpServletResponse resp) throws ServletException, IOException {
	    System.out.println(service.get());
	}
    }

    // ==========================================================================================================================================================
    public static void main(final String[] args) throws Exception {
	startVariables();

	final String dataBaseName = EMBEDDED_JEE_TEST_APP_NAME + "DB";
	final String dataBaseUrl = "jdbc:hsqldb:hsql://localhost:" + DATA_BASE_SERVER_PORT + "/" + dataBaseName;

	try (final MyEmbeddedJeeContainer embeddedJeeServer = new MyEmbeddedJeeContainer(); //
		final MyEmbeddedRdbms embeddedRdbms = new MyEmbeddedRdbms()) {

	    embeddedRdbms.addDataBase(dataBaseName, DATA_BASE_SERVER_LOGIN, DATA_BASE_SERVER_PASSWORD);
	    embeddedRdbms.start(DATA_BASE_SERVER_PORT);

	    final EmbeddedWar war = new EmbeddedWar(EMBEDDED_JEE_TEST_APP_NAME);
	    war.addMetaInfFiles(EmbeddedResource.add("beans.xml", "src/main/resources/beans.xml"));
	    war.addMetaInfFiles(EmbeddedResource.add("persistence.xml", "src/main/resources/chapter13_javaPersistence/part05_schemaGeneration/SchemaGeneration02MetaData-persistence.xml"));
	    war.addMetaInfFiles(EmbeddedResource.add("load.sql", "src/main/resources/chapter13_javaPersistence/part05_schemaGeneration/SchemaGeneration02MetaData-load.sql"));
	    war.addClasses(ServletPrincipal.class, Service.class, Student.class, Book.class);

	    final File appFile = war.exportToFile(APP_FILE_TARGET);

	    final MyEmbeddedDataSource dataSource = new MyEmbeddedDataSourceBuilder(EMBEDDED_JEE_TEST_DATA_SOURCE_NAME, dataBaseUrl)//
		    .withCredential(DATA_BASE_SERVER_LOGIN, DATA_BASE_SERVER_PASSWORD) //
		    .withDataBaseDriverClass(HSQLDB_JDBC_DRIVER) //
		    .build();

	    embeddedJeeServer.addDataSource(dataSource);
	    embeddedJeeServer.start(HTTP_PORT);

	    embeddedJeeServer.deploy(EMBEDDED_JEE_TEST_APP_NAME, appFile.getAbsolutePath());

	    // ------------ Client -----------------------------------------------------------
	    final HttpClient httpClient = HttpClientBuilder.create().build();
	    final HttpResponse response = httpClient.execute(new HttpGet("http://localhost:" + HTTP_PORT + "/" + EMBEDDED_JEE_TEST_APP_NAME + "/ServletPrincipal"));

	    System.out.println(response);

	    Thread.sleep(5000); // 5 seconds only for the server finishs its jobs...

	} catch (final Exception ex) {
	    System.out.println(ex);
	}

	downVariables();
    }

}
