apiVersion: apps/v1
kind: Deployment
metadata:
   name: wildfly
spec:
   selector:
      matchLabels:
         app: wildfly
   template:
      metadata:
         labels:
            app: wildfly
      spec:
         containers:
         -  name: wildfly
            image: jboss/wildfly
            ports:
            -  containerPort: 8080