
package br.com.fernando.view.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "livroWebService", targetNamespace = "http://webservices.view.fernando.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LivroWebService {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.fernando.view.webservices.Livro>
     */
    @WebMethod
    @WebResult(name = "livro", targetNamespace = "")
    @RequestWrapper(localName = "listarLivros", targetNamespace = "http://webservices.view.fernando.com.br/", className = "br.com.fernando.view.webservices.ListarLivros")
    @ResponseWrapper(localName = "listarLivrosResponse", targetNamespace = "http://webservices.view.fernando.com.br/", className = "br.com.fernando.view.webservices.ListarLivrosResponse")
    public List<Livro> listarLivros();

}
