package br.com.fernando.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "livros", targetNamespace = "http://application.server.fernando.com.br/", wsdlLocation = "http://localhost:8080/soa-aplicado/livros?wsdl")
public class Livros extends Service {

    private final static URL LIVROS_WSDL_LOCATION;
    private final static WebServiceException LIVROS_EXCEPTION;
    private final static QName LIVROS_QNAME = new QName("http://application.server.fernando.com.br/", "livros");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soa-aplicado/livros?wsdl");
        } catch (final MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVROS_WSDL_LOCATION = url;
        LIVROS_EXCEPTION = e;
    }

    public Livros() {
        super(__getWsdlLocation(), LIVROS_QNAME);
    }

    public Livros(final WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVROS_QNAME, features);
    }

    public Livros(final URL wsdlLocation) {
        super(wsdlLocation, LIVROS_QNAME);
    }

    public Livros(final URL wsdlLocation, final WebServiceFeature... features) {
        super(wsdlLocation, LIVROS_QNAME, features);
    }

    public Livros(final URL wsdlLocation, final QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Livros(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns ListagemLivros
     */
    @WebEndpoint(name = "ListagemLivrosPort")
    public ListagemLivros getListagemLivrosPort() {
        return super.getPort(new QName("http://application.server.fernando.com.br/", "ListagemLivrosPort"), ListagemLivros.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ListagemLivros
     */
    @WebEndpoint(name = "ListagemLivrosPort")
    public ListagemLivros getListagemLivrosPort(final WebServiceFeature... features) {
        return super.getPort(new QName("http://application.server.fernando.com.br/", "ListagemLivrosPort"), ListagemLivros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVROS_EXCEPTION != null) {
            throw LIVROS_EXCEPTION;
        }
        return LIVROS_WSDL_LOCATION;
    }

}
