apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: quarkus-jar
    app.kubernetes.io/version: latest
  name: quarkus-jar
spec:
  ports:
  - name: http
    nodePort: 31826
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-jar
    app.kubernetes: latest
  type: NodePort    