apiVersion: apps/v1
kind: Deployment
metadata:
   name: wildfly
spec:
   selector:
      matchLabels:
         app: wildfly
   replicas: 2
   template:
      metadata:
         labels:
            app: wildfly
      spec:
         containers:
         -  name: wildfly
            image: jboss/wildfly
            ports:
            -  containerPort: 8080
            -  containerPort: 9990
            -  containerPort: 7600
            -  containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
   name: wildfly-service
spec:
   selector:
      app: wildfly
   type: NodePort # For minikube        
   ports:
   -  name: web
      port: 8080
   -  name: adm
      port: 9990      
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: jetty
spec:
   selector:
      matchLabels:
         app: jetty
   replicas: 2
   template:
      metadata:
         labels:
            app: jetty
      spec:
         containers:
         -  name: jetty
            image: jetty
            ports:
            -  containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: jetty-service
spec:
   selector:
      app: jetty
   type: NodePort # For minikube        
   ports:
   -  name: web
      port: 8080   
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
   name: example-ingress
   annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
   backend:
      serviceName: default-http-backend # some whatever service ...
      servicePort: 80
   rules:
   -  host: wildfly.info
      http:
         paths:
         -  path: /
            backend:
               serviceName: wildfly-service
               servicePort: 8080
   -  host: jetty.info
      http:
         paths:
         -  path: /
            backend:
               serviceName: jetty-service
               servicePort: 8080