apiVersion: v1 
kind: ConfigMap 
metadata:
  name: game-demo
  resourceVersion: "516"
data:
  # Configuration values can be set as key-value properties
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true  
---    
apiVersion: v1 
kind: Pod 
metadata:
  name: pod-env-var 
spec:
  containers:
    - name: command-demo-container
      image: debian
      command: ["printenv"]
      args: ["PLAYER_INITIAL_LIVES", "UI_PROPERTIES_FILE_NAME"]
      env: # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.
              
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name