<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://part03_endpoint_based.chapter05_soap_basedws.fernando.com.br/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://part03_endpoint_based.chapter05_soap_basedws.fernando.com.br/" name="SimpleWebServiceService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://part03_endpoint_based.chapter05_soap_basedws.fernando.com.br/" schemaLocation="http://localhost:8080/example/SimpleWebService?xsd=1" />
		</xsd:schema>
	</types>
	<message name="sayHello">
		<part name="parameters" element="tns:sayHello" />
	</message>
	<message name="sayHelloResponse">
		<part name="parameters" element="tns:sayHelloResponse" />
	</message>
	<portType name="SimpleWebService">
		<operation name="sayHello">
			<input wsam:Action="http://part03_endpoint_based.chapter05_soap_basedws.fernando.com.br/SimpleWebService/sayHelloRequest" message="tns:sayHello" />
			<output wsam:Action="http://part03_endpoint_based.chapter05_soap_basedws.fernando.com.br/SimpleWebService/sayHelloResponse" message="tns:sayHelloResponse" />
		</operation>
	</portType>
	<binding name="SimpleWebServicePortBinding" type="tns:SimpleWebService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<operation name="sayHello">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="SimpleWebServiceService">
		<port name="SimpleWebServicePort" binding="tns:SimpleWebServicePortBinding">
			<soap:address location="http://localhost:8080/example/SimpleWebService" />
		</port>
	</service>
</definitions>