<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://simplewebservice.com.br" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://simplewebservice.com.br" name="SimpleWebService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://simplewebservice.com.br" schemaLocation="http://localhost:18080/embeddedJeeContainerTest/SimpleWebService?xsd=1" />
		</xsd:schema>
	</types>
	<message name="sayHello">
		<part name="parameters" element="tns:sayHello" />
	</message>
	<message name="sayHelloResponse">
		<part name="parameters" element="tns:sayHelloResponse" />
	</message>
	<message name="sayHelloAgain">
		<part name="parameters" element="tns:sayHelloAgain" />
	</message>
	<message name="sayHelloAgainResponse">
		<part name="parameters" element="tns:sayHelloAgainResponse" />
	</message>
	<portType name="SimpleEndpointInterface">
		<operation name="sayHello">
			<input wsam:Action="http://simplewebservice.com.br/SimpleEndpointInterface/sayHelloRequest" message="tns:sayHello" />
			<output wsam:Action="http://simplewebservice.com.br/SimpleEndpointInterface/sayHelloResponse" message="tns:sayHelloResponse" />
		</operation>
		<operation name="sayHelloAgain">
			<input wsam:Action="http://simplewebservice.com.br/SimpleEndpointInterface/sayHelloAgainRequest" message="tns:sayHelloAgain" />
			<output wsam:Action="http://simplewebservice.com.br/SimpleEndpointInterface/sayHelloAgainResponse" message="tns:sayHelloAgainResponse" />
		</operation>
	</portType>
	<binding name="SimplePortBinding" type="tns:SimpleEndpointInterface">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<operation name="sayHello">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="sayHelloAgain">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="SimpleWebService">
		<port name="SimplePort" binding="tns:SimplePortBinding">
			<soap:address location="http://localhost:18080/embeddedJeeContainerTest/SimpleWebService" />
		</port>
	</service>
</definitions>