apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: wildfly-scaler
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: wildfly # spec.scaleTargetRef tells HPA which scalable controller to scale (Deployment, RepicaSet or ReplicationController).   
   minReplicas: 3
   maxReplicas: 10
   targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: wildfly
spec:
   selector:
      matchLabels:
         app: wildfly
   template:
      metadata:
         labels:
            app: wildfly
      spec:
         containers:
         -  name: wildfly
            image: jboss/wildfly
            ports:
            -  containerPort: 8080