version: "3.7"
services:
    loadbalancer:
        build: lb
        environment:
            APPLICATION_PORT: 3000
        ports:
        - 8080:80
        networks:
        - lab
    red:
        build: app
        environment:
            COLOR: "red"
        labels:
            role: backend
        ports:
        - 3000
        networks:
        - lab
    green:
        build: app
        environment:
            COLOR: "green"
        labels:
            role: backend
        ports:
        - 3000
        networks:
        - lab
    white:
        build: app
        environment:
            COLOR: "white"
        labels:
            role: backend
        ports:
        - 3000
        networks:
        - lab
networks:
    lab:
