apiVersion: v1
kind: Service
metadata: 
  name: wildfly-service
spec: 
  selector: 
    app: wildfly-rc-pod
  ports:
    - name: web
      port: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: wildfly-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wildfly-rc-pod
    spec:
      containers:
      - name: wildfly
        image: jboss/wildfly:10.1.0.Final
        ports:
        - containerPort: 8080
