apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: hello
spec:
  schedule: 0/1 * * * ?
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloworld
            image: busybox
            args:
            - /bin/bash
            - -c
            - date; echo Hello World!
          restartPolicy: OnFailure
