
package br.com.fernando.server.application.autores.v1;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "autoresCallback", targetNamespace = "http://fernando.com.br/server/application/autores/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.fernando.core.estoque.v1.ObjectFactory.class,
    br.com.fernando.core.usuarios.v1.ObjectFactory.class,
    br.com.fernando.server.application.autores.v1.ObjectFactory.class
})
public interface AutoresCallback {


    /**
     * 
     * @param parameters
     */
    @WebMethod
    @Oneway
    public void solicitarRelacaoDeAutoresCallback(
        @WebParam(name = "solicitarRelacaoDeAutoresResponse", targetNamespace = "http://fernando.com.br/server/application/autores/v1", partName = "parameters")
        SolicitarRelacaoDeAutoresResponse parameters);

}
