
package br.com.fernando.server.application.autores.v1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.fernando.core.estoque.v1.Autor;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "autores", targetNamespace = "http://fernando.com.br/server/application/autores/v1")
@XmlSeeAlso({
    br.com.fernando.core.estoque.v1.ObjectFactory.class,
    br.com.fernando.core.usuarios.v1.ObjectFactory.class,
    br.com.fernando.server.application.autores.v1.ObjectFactory.class
})
public interface Autores {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.fernando.core.estoque.v1.Autor>
     */
    @WebMethod(action = "autores/ListarAutores")
    @WebResult(name = "autor", targetNamespace = "")
    @RequestWrapper(localName = "listarAutores", targetNamespace = "http://fernando.com.br/server/application/autores/v1", className = "br.com.fernando.server.application.autores.v1.ListarAutores")
    @ResponseWrapper(localName = "listarAutoresResponse", targetNamespace = "http://fernando.com.br/server/application/autores/v1", className = "br.com.fernando.server.application.autores.v1.ListarAutoresResponse")
    public List<Autor> listarAutores();

    /**
     * 
     * @param desde
     * @return
     *     returns java.util.List<br.com.fernando.core.estoque.v1.Autor>
     */
    @WebMethod
    @WebResult(name = "autor", targetNamespace = "")
    @RequestWrapper(localName = "solicitarRelacaoDeAutores", targetNamespace = "http://fernando.com.br/server/application/autores/v1", className = "br.com.fernando.server.application.autores.v1.SolicitarRelacaoDeAutores")
    @ResponseWrapper(localName = "solicitarRelacaoDeAutoresResponse", targetNamespace = "http://fernando.com.br/server/application/autores/v1", className = "br.com.fernando.server.application.autores.v1.SolicitarRelacaoDeAutoresResponse")
    @Action(input = "autores/solicitarRelacaoDeAutores", output = "autores/solicitarRelacaoDeAutoresResponse")
    public List<Autor> solicitarRelacaoDeAutores(
        @WebParam(name = "desde", targetNamespace = "")
        XMLGregorianCalendar desde);

}
