package br.com.fernando.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.com.fernando.core.Autor;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebService(name = "AutoresService", targetNamespace = "http://application.server.fernando.com.br/")
@XmlSeeAlso({ ObjectFactory.class })
public interface AutoresService {

    /**
     * 
     * @return returns java.util.List<com.knight.estoque.servicos.Autor>
     */
    @WebMethod
    @WebResult(name = "autor", targetNamespace = "")
    @RequestWrapper(localName = "listarAutores", targetNamespace = "http://application.server.fernando.com.br/", className = "com.knight.estoque.servicos.ListarAutores")
    @ResponseWrapper(localName = "listarAutoresResponse", targetNamespace = "http://application.server.fernando.com.br/", className = "com.knight.estoque.servicos.ListarAutoresResponse")
    public List<Autor> listarAutores();

}
