kind: PersistentVolume
apiVersion: v1
metadata:
   name: couchbase-pv
   labels:
      type: amazonEBS
spec:
   capacity:
      storage: 5Gi
   accessModes:
   - ReadWriteOnce
   awsElasticBlockStore:
      volumeID: vol-0e04a9f45ad0cc01d
      fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: couchbase-pvc
   labels:
      type: amazonEBS
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 3Gi