apiVersion: v1
kind: Service
metadata:
   name: couchbase-service
spec:
   selector:
      app: couchbase-rc-pod
   ports:
   -  name: admin
      port: 8091
   -  name: views
      port: 8092
   -  name: query
      port: 8093
   -  name: memcached
      port: 11210
---
apiVersion: v1
kind: ReplicationController # Use Deployment (this is just a example)
metadata:
   name: couchbase-rc
spec:
   replicas: 1
   template:
      metadata:
         name: couchbase-rc-pod
         labels:
            name: couchbase-rc-pod
            context: couchbase-pv
            app: couchbase-rc-pod
      spec:
         containers:
         -  name: couchbase
            image: arungupta/oreilly-couchbase
            volumeMounts: # The dir /opt/couchbase/var is the directory where the Couchbase server stores all the data. The mount is given the name mypd.
            -  mountPath: "/opt/couchbase/var" # The mount path as seen in the container. The directory in your pod.
               name: mypd # The name of the volume. This name must be the same in both the containers and volumes sections
            ports:
            -  containerPort: 8091
            -  containerPort: 8092
            -  containerPort: 8093
            -  containerPort: 11210
         volumes:
         -  name: mypd
            persistentVolumeClaim:
               claimName: couchbase-pvc # The PVC that was created in the volume-pv-####
---
apiVersion: batch/v1
kind: Job
metadata:
   name: bootiful-couchbase
   labels:
      name: bootiful-couchbase-pod
spec:
   template:
      metadata:
         name: bootiful-couchbase-pod
      spec:
         containers:
         -  name: bootiful-couchbase
            image: fernando/bootiful-couchbase
            imagePullPolicy: IfNotPresent
         restartPolicy: Never