apiVersion: v1
kind: Service
metadata:
   name: mysql-service
   namespace: default
spec:
   ports:
   -  name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
   selector:
      app: mysql # (*1*)
   type: NodePort # For minikube
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql-deployment
spec:
   selector:
      matchLabels:
         app: mysql # (*1*)
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: mysql
            context: mysql-pv-volume # (*5*)
      spec:
         containers:
         -  image: mysql:5.7.28
            name: mysql
            env:
            -  name: MYSQL_USER
               value: 'root' # don't remove '
            -  name: MYSQL_ROOT_PASSWORD
               value: '123' # don't remove '
            -  name: MYSQL_DATABASE
               value: 'mydb' # don't remove '
            ports:
            -  containerPort: 3306
               name: mysql
            imagePullPolicy: IfNotPresent
            volumeMounts:
            -  name: mysql-persistent-storage
               mountPath: /var/lib/mysql
         volumes:
         -  name: mysql-persistent-storage
            persistentVolumeClaim:
               claimName: mysql-pv-claim # (*3*)
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: mysql-class # (*2*)
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pv-claim # (*3*)
spec:
   storageClassName: mysql-class # (*2*)
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-pv-volume # (*5*)
   labels:
      type: local
spec:
   storageClassName: mysql-class # (*2*)
   capacity:
      storage: 2Gi
   accessModes:
   - ReadWriteOnce
   hostPath:
      path: /mnt/data
---
apiVersion: batch/v1
kind: Job
metadata:
   name: bootiful-mysql
   labels:
      name: bootiful-mysql-pod
spec:
   template:
      metadata:
         name: bootiful-mysql-pod
      spec:
         containers:
         -  name: bootiful-mysql
            image: fernando/bootiful-mysql
            imagePullPolicy: IfNotPresent
         restartPolicy: Never