<<<<<<< HEAD
AWSTemplateFormatVersion: "2010-09-09"
=======
AWSTemplateFormatVersion: '2010-09-09'
>>>>>>> 293ba8b491004f920bc29762e085f49a73d1fa17
Description: Attach an EBS volume to the EC2 instance, retaining original resources
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
<<<<<<< HEAD
      ImageId: ami-04eeb630f180cea95
=======
      ImageId: ami-0440d3b780d96b29d
>>>>>>> 293ba8b491004f920bc29762e085f49a73d1fa17
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup
  MyVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
      Size: 10
  MyVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyInstance
      VolumeId: !Ref MyVolume
<<<<<<< HEAD
      Device: /dev/sdf
=======
      Device: /dev/sdf
>>>>>>> 293ba8b491004f920bc29762e085f49a73d1fa17
